// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

type AssetPlatformIdList = { [chain in string]: string };

const ASSET_PLATFORMS_IDS_LIST: AssetPlatformIdList = JSON.parse(
  '{"1":"ethereum","10":"optimistic-ethereum","25":"cronos","56":"binance-smart-chain","57":"syscoin","66":"okex-chain","70":"hoo-smart-chain","82":"meter","88":"tomochain","100":"xdai","106":"velas","122":"fuse","128":"huobi-token","137":"polygon-pos","250":"fantom","288":"boba","321":"kucoin-community-chain","361":"theta","1088":"metis-andromeda","1284":"moonbeam","1285":"moonriver","2001":"milkomeda-cardano","8545":"shiden network","9001":"evmos","10000":"smartbch","42161":"arbitrum-one","42220":"celo","42262":"oasis","43114":"avalanche","333999":"polis-chain","1313161554":"aurora","1666600000":"harmony-shard-0"}'
);

export { ASSET_PLATFORMS_IDS_LIST, AssetPlatformIdList };
